// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efoljtbqmwzchqjdyxwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmb2xqdGJxbXd6Y2hxamR5eHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjQ0MTcsImV4cCI6MjA3MTkwMDQxN30.rqmZbGyQHv8SAMfQmbqlZcxkXkLcqAlQrzlr6SY39mA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});